Spotlight.Reports/Controllers/ReportController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Spotlight.Reports.Filters;
using Spotlight.Reports.Models;
using SpotlightCoin.BAL;
using SpotlightCoin.Model.Domain;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;


namespace Spotlight.Reports.Controllers
{
    [SessionFilter]
    [HandleException]
    public class ReportController : Controller
    {
        private IReport _IReport;

        public ReportController(IReport report)
        {


            this._IReport = report;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        /// <summary>
        /// Need to validate the credential
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Login(UserLogin user)
        {
            UserLogin userLogin = new UserLogin();
            if (ModelState.IsValid)
            {
                //UserLogin userLogin = new UserLogin();
                userLogin.UserName = user.UserName;
                userLogin.Password = user.Password;
            }
            StringBuilder traceInformation = new StringBuilder();

            Uri basUrl = new Uri("http://localhost:52223/api/Report/Login");
            //string UserIdUrl = Common.Common.GetAPIBaseURL() + Constant.UserIdPath;

            try
            {

                if (userLogin.UserName != null & user.Password != null)
                {
                    var byteContent = JsonConvert.SerializeObject(userLogin);
                    var buffer = Encoding.UTF8.GetBytes(byteContent);

                    using (HttpClient client = new HttpClient())
                    {
                        var content = new ByteArrayContent(buffer);
                        var response = client.PostAsync(basUrl, content).Result;
                        var responseString = response.Content.ReadAsStringAsync().Result;
                        //var tokenDetails = JsonConvert.DeserializeObject<TokenData>(responseString);


                    }
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                throw;
            }
            return View();
        }

        //public IActionResult Index()
        //{
        //    IEnumerable<DailyPOSRevenueFiscalYOY> data = _IReport.GetDailyPOSRevenueFiscalYOY();
        //    return View(data);
        //}

        public IActionResult GetReportList()
        {
            List<ReportList> reportList = new List<ReportList>
            {
                new ReportList() {  ReportName = "Daily POS Revenue Fiscal YOY",  ReportActionName = "GetDailyPOSRevenueFiscalYOY" },
                new ReportList() {  ReportName = "Daily Revenue Report",  ReportActionName = "GetDailyRevenueReport" },
                new ReportList() {  ReportName = "Hosted Player Activity",  ReportActionName = "GetHostedPlayerActivity" },
                new ReportList() {  ReportName = "Month End Slot Marketing Analysis",  ReportActionName = "GetMonthEndSlotMarketingAnalysis" },
                new ReportList() {  ReportName = "New Acquisition by Host by Month",  ReportActionName = "GetNewAcquisitionbyHostbyMonth" },
                new ReportList() {  ReportName = "New Member by ADT or ADA Report",  ReportActionName = "GetNewMemberbyADTorADAReport" },
                new ReportList() {  ReportName = "Patron Carded Revenue Trends",  ReportActionName = "GetPatronCardedRevenueTrends" },
                new ReportList() {  ReportName = "Patron Listing",  ReportActionName = "GetPatronListing" },
                new ReportList() {  ReportName = "Tables with Play by Day",  ReportActionName = "GetTableswithPlaybyDay" },
                new ReportList() {  ReportName = "Top Twenty Winners and Losers",  ReportActionName = "GetTopTwentyWinnersandLosers" }
            };
            return View(reportList);
        }

        public IActionResult GetDailyPOSRevenueFiscalYOY()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetDailyPOSRevenueFiscalYOYSearch(ReportSearchEntity model)
        {
            IEnumerable<DailyPOSRevenueFiscalYOY> data = _IReport.GetDailyPOSRevenueFiscalYOY(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetDailyPOSRevenueFiscalYOYPartial");
        }
        public IActionResult ExportToExcel()
        {
            return View("_GetDailyPOSRevenueFiscalYOYPartial");
            //return View(SampleData.DataGridEmployees.Take(10).ToList<Employee>());
        }


        public IActionResult GetDailyRevenueReport()
        {
            return View();
        }

        public IActionResult GetDailyRevenueReportSearch(ReportSearchEntity model)
        {
            IEnumerable<DailyRevenueReport> data = _IReport.GetDailyRevenueReport(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetDailyRevenueReportPartial");
        }

        public IActionResult GetHostedPlayerActivity()
        {

            return View();
        }

        public IActionResult GetHostedPlayerActivitySearch(ReportSearchEntity model)
        {
            IEnumerable<HostedPlayerActivity> data = _IReport.GetHostedPlayerActivity(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetHostedPlayerActivityPartial");
        }

        public IActionResult GetMonthEndSlotMarketingAnalysis()
        {
            ChartInpuControlData data = _IReport.GetChartInputData();
            ViewBag.data = data;
            return View();
        }


        public IActionResult GetMonthEndSlotMarketingAnalysisSearch(ReportSearchEntity model)
        {

            ChartData data = _IReport.GetChartData(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetMonthEndSlotMarketingAnalysisPartial");
        }

        public IActionResult GetNewAcquisitionbyHostbyMonth()
        {
            return View();
        }

        public IActionResult GetNewAcquisitionbyHostbyMonthSearch(ReportSearchEntity model)
        {
            IEnumerable<NewAcquisitionbyHostbyMonth> data = _IReport.GetNewAcquisitionbyHostbyMonth(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetNewAcquisitionbyHostbyMonthPartial");
        }

        public IActionResult GetNewMemberbyADTorADAReport()
        {
            //IEnumerable<NewMemberbyADTorADAReport> data = _IReport.GetNewMemberbyADTorADAReport();
            return View();
        }

        public IActionResult GetNewMemberbyADTorADAReportSearch(ReportSearchEntity model)
        {
            IEnumerable<NewMemberbyADTorADAReport> data = _IReport.GetNewMemberbyADTorADAReport(model);
            ViewBag.data = data;
            ViewBag.ReportType = model.Type;
            ViewBag.searchParameter = model;
            return PartialView("_GetNewMemberbyADTorADAReportPartial");
        }

        public IActionResult GetPatronCardedRevenueTrends()
        {
            //IEnumerable<PatronCardedRevenueTrends> data = _IReport.GetPatronCardedRevenueTrends();
            return View();
        }

        public IActionResult GetPatronCardedRevenueTrendsSearch(ReportSearchEntity model)
        {
            IEnumerable<PatronCardedRevenueTrends> data = _IReport.GetPatronCardedRevenueTrends(model);
            ViewBag.data = data;
            ViewBag.ReportType = model.ReportType;
            ViewBag.searchParameter = model;
            return PartialView("_GetPatronCardedRevenueTrendsPartial");
        }

        public IActionResult GetPatronListing()
        {
            //IEnumerable<PatronListingMain> data = _IReport.GetPatronListing();
            return View();
        }

        public IActionResult GetPatronListingSearch(ReportSearchEntity model)
        {
            IEnumerable<PatronListingMain> data = _IReport.GetPatronListing(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetPatronListingPartial");
        }


        public IActionResult GetTableswithPlaybyDay()
        {
            //IEnumerable<TableswithPlaybyDay> data = _IReport.GetTableswithPlaybyDay();
            return View();
        }

        public IActionResult GetTableswithPlaybyDaySearch(ReportSearchEntity model)
        {
            IEnumerable<TableswithPlaybyDay> data = _IReport.GetTableswithPlaybyDay(model);
            ViewBag.data = data;
            ViewBag.searchParameter = model;
            return PartialView("_GetTableswithPlaybyDayPartial");
        }


        public IActionResult GetTopTwentyWinnersandLosers()
        {
            //IEnumerable<TopTwentyWinnersandLosers> data = _IReport.GetTopTwentyWinnersandLosers();
            return View();
        }

        public IActionResult GetTopTwentyWinnersandLosersSearch(ReportSearchEntity model)
        {
            IEnumerable<TopTwentyWinnersandLosers> data = _IReport.GetTopTwentyWinnersandLosers(model);
            ViewBag.data = data;
            ViewBag.ReportType = model.ReportType;
            ViewBag.searchParameter = model;
            return PartialView("_GetTopTwentyWinnersandLosersPartial");
        }

        public IActionResult GetHostListMultiple(ReportSearchEntity model)
        {
            IEnumerable<HostedPlayerActivityHost> data = _IReport.GetHostList(model);
            ViewBag.searchParameter = model;
            return PartialView("_HostListMultiplePartial", data);
        }

        public IActionResult GetHostList(ReportSearchEntity model)
        {

Spotlight.Reports/Views/Report/GetDailyPOSRevenueFiscalYOY.cshtml
@using SpotlightCoin.Model.Domain

@{
    ViewBag.Title = "GetDailyPOSRevenueFiscalYOY";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div>
    <form asp-action="GetDailyPOSRevenueFiscalYOYSearch" id="postForm">
        <!-- form content-->
        <div class="long-title">
            <h3>Daily POS Revenue Fiscal YOY</h3>
        </div>
        <div class="row">
            <div class="col-md-4">
                @(Html.Label("Start Date : "))
                @(Html.DevExtreme().DateBox().ID("txtStartDate").Type(DateBoxType.Date).Name("StartDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onStartDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">

                @(Html.Label("End Date : "))
                @(Html.DevExtreme().DateBox().ID("txtEndDate").Type(DateBoxType.Date).Name("EndDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onEndDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))
            </div>
        </div>
    </form>
</div>

<div id="dvYOO">
</div>

<script>
    $("#postForm").on("submit", function (e) {
        $('#loading').show();
        e.preventDefault()
        $.ajax({
            method: "POST",
            url: "/Report/GetDailyPOSRevenueFiscalYOYSearch",
            data: $("#postForm").serialize(),
            success: function (response) {
                $("#dvYOO").html(response);
              //  $('#loading').hide();
            },
            failure: function () {
                $('#loading').hide();
            }
        })
    })

</script>

Spotlight.Reports/Views/Report/GetDailyRevenueReport.cshtml
@using DevExtreme.AspNet.Mvc
@using SpotlightCoin.Model.Domain
@{
    ViewBag.Title = "GetDailyRevenueReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
   
    <form asp-action="GetDailyRevenueReportSearch" id="postForm">
        <!-- form content-->

        <div class="long-title">
            <h3>Daily Revenue Report</h3>
        </div>
        <div class="row">
            <div class="col-md-4">
                @(Html.Label("Start Date : "))
                @(Html.DevExtreme().DateBox().ID("txtStartDate").Type(DateBoxType.Date).Name("StartDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onStartDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">
                @(Html.Label("End Date : "))
                @(Html.DevExtreme().DateBox().ID("txtEndDate").Type(DateBoxType.Date).Name("EndDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onEndDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))
            </div>
        </div>
        @*}*@
    </form>
</div>

<div id="dvDailyRevenueReport">
</div>

<script>
    $("#postForm").on("submit", function (e) {
        $('#loading').show();
        e.preventDefault()
        $.ajax({
            method: "POST",
            url:"/Report/GetDailyRevenueReportSearch",
            data: $("#postForm").serialize(),
            success: function (response) {
                $("#dvDailyRevenueReport").html(response);
               // $('#loading').hide();
            },
            failure: function () {
                $('#loading').hide();
            }
        })
    })

</script>

Spotlight.Reports/Views/Report/GetHostedPlayerActivity.cshtml
@using DevExtreme.AspNet.Mvc
@using SpotlightCoin.Model.Domain

@{
    ViewBag.Title = "GetHostedPlayerActivity";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div>

    <form asp-action="GetHostedPlayerActivitySearch" id="postForm">
        <!-- form content-->
        <link href="~/lib/multiple-select.css" rel="stylesheet" />
        <div class="long-title">
            <h3>Hosted Player Activity</h3>
        </div>
        <div class="row">
            <div class="col-md-3">
                @(Html.Label("Start Date : "))
                @(Html.DevExtreme().DateBox().ID("txtStartDate").Type(DateBoxType.Date).Name("StartDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onStartDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
               
            </div>
            <div class="col-md-3">
                @(Html.Label("End Date : "))
                @(Html.DevExtreme().DateBox().ID("txtEndDate").Type(DateBoxType.Date).Name("EndDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onEndDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
               

            </div>
            <div class="col-md-3">
                @(Html.Label("Host : "))
                <div id="chkHost" class="chkHost">
                    <div class="ms-parent " style="width: 146.813px;"><button type="button" class="ms-choice"><span class=""></span><div class=""></div></button></div>
                </div>
            </div>
            <div class="col-md-3">
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))

                @(Html.DevExtreme().Popup()
                        .ID("popShowHide")
                        .Content("Please select the Host")
                        .Width(300)
                        .Height(250)
                        .ShowTitle(true)
                        .Title("Alert")
                        .CloseOnOutsideClick(true)
                        .ShowCloseButton(true))
            </div>
        </div>
    </form>
</div>

<div id="dvHostedPlayerActivity">
 
</div>

<script>
   

    function bindHost() {
        if (startDateOldVal != null && endDateOldVal != null && startDateOldVal <= endDateOldVal) {
            $('#loading').show();
            $.ajax({
                method: "POST",
                data: $("#postForm").serialize(),
                url: "/Report/GetHostListMultiple",
                success: function (response) {
                    $("#chkHost").html(response);
                    $('#loading').hide();
                }
            });
        }

    }

    $("#postForm").on("submit", function (e) {
        if ($("div .chkHost select").val().length == 0) {            
            $("#popShowHide").dxPopup("instance").show()
            return false;
        }
        $('#loading').show();
        e.preventDefault()
        $('#HostId').val(hostData.data().multipleSelect.getSelects().join())
        $.ajax({
            method: "POST",
            url: "/Report/GetHostedPlayerActivitySearch",
            data: $("#postForm").serialize(),
            success: function (response) {
                $("#dvHostedPlayerActivity").html(response);           
            },
            failure: function () {
                $('#loading').hide();
            }
        });
    })


    function getLoadPanelInstance() {
        return $("#loadPanel").dxLoadPanel("instance");
    }

</script>

<style>
    .ms-parent {
        width: 200px !important;
    }
</style>

Spotlight.Reports/Views/Report/GetMonthEndSlotMarketingAnalysis.cshtml
@using DevExtreme.AspNet.Mvc
@using SpotlightCoin.Model.Domain
@{
    ViewBag.Title = "GetMonthEndSlotMarketingAnalysis";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ChartInpuControlData data = (ViewData["Data"] as ChartInpuControlData);

}

<div>

    <form asp-action="GetMonthEndSlotMarketingAnalysisSearch" id="postForm">
        <!-- form content-->

        <div class="long-title">
            <h3>Month End Slot Marketing Analysis</h3>
        </div>
        <div class="row">
            <div class="col-md-4">
                @(Html.Label("Begin Year: "))
                @(Html.DevExtreme().SelectBox().DataSource(data.ReportYearStart.ToList()).ID("ddlBegin").DisplayExpr("Year").ValueExpr("YearCode").Name("Begin").OnValueChanged("onBeginEndValueChanged").ValidationError("Please select Begin Year <= End Year"))

            </div>
            <div class="col-md-4">
                @(Html.Label("End Year: "))
                @(Html.DevExtreme().SelectBox().DataSource(data.ReportYearStart.ToList()).ID("ddlEnd").DisplayExpr("Year").ValueExpr("YearCode").Name("End").OnValueChanged("onBeginEndValueChanged").ValidationError("Please select End Year >= Begin Year"))
            </div>

            <div class="col-md-4">
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))
            </div>
        </div>
    </form>
</div>

<div id="dvMonthEndSlotMarketingAnalysis">
</div>

<script>
    $("#postForm").on("submit", function (e) {
        $('#loading').show();
        e.preventDefault()
        $.ajax({
            method: "POST",
            url: "/Report/GetMonthEndSlotMarketingAnalysisSearch",
            data: $("#postForm").serialize(),
            success: function (response) {
                $("#dvMonthEndSlotMarketingAnalysis").html(response);
            },
            failure: function () {
                $('#loading').hide();
            }
        })
    });



    var beginYear;
    var endYear;

    $(function () {
        beginYear = $("#ddlBegin").dxSelectBox({
        }).dxSelectBox("instance");
        endYear = $("#ddlEnd").dxSelectBox({
        }).dxSelectBox("instance");
    });

    var onBeginEndValueChanged = function (e) {
        if (beginYear.option("value") !== null && endYear.option("value") !== null) {

            if (beginYear.option("value") <= endYear.option("value")) {

            }
            else {

                if (e.component._$element.attr('id') === "ddlBegin") {
                    beginYear.option("value", false);
                } else {
                    endYear.option("value", false);
                }

            }
        }
    }
</script>

Spotlight.Reports/Views/Report/GetNewAcquisitionbyHostbyMonth.cshtml
@using DevExtreme.AspNet.Mvc
@using SpotlightCoin.Model.Domain

@{
    ViewBag.Title = "GetNewAcquisitionbyHostbyMonth";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>

    <form asp-action="GetNewAcquisitionbyHostbyMonthSearch" id="postForm">

        <div class="long-title">
            <h3>New Acquisition by Host by Month</h3>
        </div>
        <div class="row">
            <div class="col-md-4">
                @(Html.Label("Start Date : "))
                @(Html.DevExtreme().DateBox().ID("txtStartDate").Type(DateBoxType.Date).Name("StartDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onStartDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">
                @(Html.Label("End Date : "))
                @(Html.DevExtreme().DateBox().ID("txtEndDate").Type(DateBoxType.Date).Name("EndDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onEndDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-4">
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))
            </div>
        </div>
    </form>
</div>

<div id="dvNewAcquisitionbyHostbyMonth">
</div>

<script>
    $("#postForm").on("submit", function (e) {
        $('#loading').show();
    e.preventDefault()
    $.ajax({
        method: "POST",
        url: "/Report/GetNewAcquisitionbyHostbyMonthSearch",
        data: $("#postForm").serialize(),
        success: function (response) {
            $("#dvNewAcquisitionbyHostbyMonth").html(response);
        },
        failure: function () {
            $('#loading').hide();
        }
    })
})

</script>

Spotlight.Reports/Views/Report/GetNewMemberbyADTorADAReport.cshtml
@using DevExtreme.AspNet.Mvc

@{
    ViewBag.Title = "GetNewMemberbyADTorADAReport";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var ReportType = new[] {new {
        ID = 0,
        Name = "All Player"

    },
     new {
        ID = 1,
        Name = "New Player"

    } };

    var Type = new[] {new {
        ID = 1,
        Name = "ADT"

    },
     new {
        ID = 2,
        Name = "ADA Win"

    },
     new {
        ID = 3,
        Name = "ADA Loss"

    } };
}

<div>

    <form asp-action="GetGetNewMemberbyADTorADAReportSearch" id="postForm">
        <div class="long-title">
            <h3>New Member by ADT or ADA Report</h3>
        </div>
        <div class="row">
            <div class="col-md-2">
                @(Html.Label("Start Date : "))
                @(Html.DevExtreme().DateBox().ID("txtStartDate").Type(DateBoxType.Date).Name("StartDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onStartDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>
            <div class="col-md-2">
                @(Html.Label("End Date : "))
                @(Html.DevExtreme().DateBox().ID("txtEndDate").Type(DateBoxType.Date).Name("EndDate").Placeholder("MM/DD/YYYY").AcceptCustomValue(true).OnValueChanged("onEndDateValueChanged").Max(DateTime.Now).InvalidDateMessage("Value must be valid date")

                )
            </div>

            <div class="col-sd-2">

                @(Html.Label("Type : "))
                @(Html.DevExtreme().SelectBox().DataSource(Type).DisplayExpr("Name")
                                                    .ValueExpr("ID").Name("Type"))
            </div>
            
            <div class="col-md-2">
                @(Html.Label("Amount : "))
                @(Html.DevExtreme().NumberBox().ID("txtAmount").Name("Amount").Placeholder("Amount"))
            </div>
            <div class="col-md-2">
                @(Html.Label("Report Type : "))
                @(Html.DevExtreme().SelectBox().DataSource(ReportType).DisplayExpr("Name")
                                                            .ValueExpr("ID").Name("ReportType"))
            </div>
            <div >
                @(Html.DevExtreme().Button().UseSubmitBehavior(true).Text("Search").Type(ButtonType.Default))
            </div>
        </div>
    </form>
</div>

<div id="dvNewMemberbyADTorADAReport">
</div>

<script>
    $("#postForm").on("submit", function (e) {
        $('#loading').show();
        e.preventDefault()
        $.ajax({
            method: "POST",
            url: "/Report/GetNewMemberbyADTorADAReportSearch",
            data: $("#postForm").serialize(),
            success: function (response) {
                $("#dvNewMemberbyADTorADAReport").html(response);
            },
            failure: function () {
                $('#loading').hide();
            }
        })
    })

</script>

Spotlight.Reports/Views/Report/GetReportList.cshtml
@model IEnumerable<Spotlight.Reports.Models.ReportList>

@{

    List<Spotlight.Reports.Models.ReportList> data = Model.ToList();
}

<link href="~/lib/StyleSheet.css" rel="stylesheet" />
<script type="text/javascript">

    menuType = "ReportList";

</script>
<div class="long-title">
    <h3>
        Please Select Report</h3>
</div>
<div class="all-report">

    @for (int index = 0; index < data.Count(); index += 3)
    {


        <div class="report-list">
            <a href="@Url.Action(data[index].ReportActionName, "Report")" title="The Contact ROI Report is a CxO report that reflects the Increase/Decrease of Trips, Theo, ADT, Actual and ADA prior to the first contact made with the patron vs the same time period after the last contact made with the patron.">
                <div class="custom-icon  @data[index].ReportName.Trim().Replace(" ","").ToLower()">
                    <i>

                        <img src="@Url.Content("~/images/"+data[index].ReportName.Trim().Replace(" ","").ToLower()+".png")" alt="@data[index].ReportName.Trim().Replace(" ","").ToLower()">
                    </i>
                </div>
                <div class="custom-report-data">
                    <div class="custom-text">
                        @data[index].ReportName
                    </div>
                    <div class="custom-arrow">
                        <i class="fa fa-angle-right"></i>
                    </div>
                </div>
            </a>
        </div>

        @if (index + 1 < data.Count())
        {
            <div class="report-list mid-col">
                <a href="@Url.Action(data[index + 1].ReportActionName, "Report")" title="The Contact ROI Report is a CxO report that reflects the Increase/Decrease of Trips, Theo, ADT, Actual and ADA prior to the first contact made with the patron vs the same time period after the last contact made with the patron.">
                    <div class="custom-icon @data[index+1].ReportName.Trim().Replace(" ","").ToLower()">
                        <i>
                            <img src="@Url.Content("~/images/"+data[index+1].ReportName.Trim().Replace(" ","").ToLower()+".png")" alt="@data[index+1].ReportName.Trim().Replace(" ","").ToLower()">
                        </i>
                    </div>
                    <div class="custom-report-data">
                        <div class="custom-text">
                            @data[index + 1].ReportName
                        </div>
                        <div class="custom-arrow">
                            <i class="fa fa-angle-right"></i>
                        </div>
                    </div>
                </a>
            </div>

        }

        @if (index + 2 < data.Count())
        {
            <div class="report-list">
                <a href="@Url.Action(data[index + 2].ReportActionName, "Report")" title="The Contact ROI Report is a CxO report that reflects the Increase/Decrease of Trips, Theo, ADT, Actual and ADA prior to the first contact made with the patron vs the same time period after the last contact made with the patron.">
                    <div class="custom-icon @data[index+2].ReportName.Trim().Replace(" ","").ToLower()">
                        <i>
                            <img src="@Url.Content("~/images/"+data[index+2].ReportName.Trim().Replace(" ","").ToLower()+".png")" alt="@data[index+2].ReportName.Trim().Replace(" ","").ToLower()">
                        </i>
                    </div>
                    <div class="custom-report-data">
                        <div class="custom-text">
                            @data[index + 2].ReportName
                        </div>
                        <div class="custom-arrow">
                            <i class="fa fa-angle-right"></i>
                        </div>
                    </div>
                </a>
            </div>
        }
    }



</div>